### ISSUE TITLE
Blank white screen after logging in

### ISSUE THREAD

**Issue by XantherBanter** [shlagevuk/docker-hakuneko#1]
**Describe the bug**
After running docker run command (with added flags to work with [Cloudbox's](https://github.com/Cloudbox/Cloudbox/wiki/Add-Your-Own-Docker-Container-Into-Cloudbox) setup), it only displays blank white screen after logging in into Guacamole.

**To Reproduce**

1. Run command on readme. Flags added
2. Login via `https://hakuneko.domain.ltd`
3. Browser displays white screen.

**Expected behavior**
Hakuneko GUI is displayed after logging in

**Logs**
[hakuneko.log](https://github.com/shlagevuk/docker-hakuneko/files/4779611/hakuneko.log)

**System Information**
Server: Ubuntu 18.04 LTS with [Cloudbox](https://github.com/Cloudbox/Cloudbox)
PC: Windows 10 on Chrome 83.0.4103.97

**Additional context**
Docker run command used

```sh
docker run -d \
  --name=hakuneko \
  -e PGID=1001 \
  -e PUID=1000 \
  -e TZ=Asia/Singapore \
  -e GUAC_USER=user \
  -e GUAC_PASS=xxxxxyyyyyzzzzz \
  --label com.github.cloudbox.cloudbox_managed=true \
  -v /opt/hakuneko:/config \
  -v /mnt/unionfs/Media/Comics:/manga \
  --restart unless-stopped \
  --cap-add=CAP_SYS_ADMIN \
  --network=cloudbox  \
  --network-alias=hakuneko  \
  -e VIRTUAL_HOST=hakuneko.domain.ltd  \
  -e VIRTUAL_PORT=8080 \
  -e LETSENCRYPT_HOST=hakuneko.domain.ltd  \
  -e LETSENCRYPT_EMAIL=hi@domain.ltd  \
  shlagevuk/hakuneko
```

**Comment by shlagevuk** [comment]
Thanks for the bug report, I'm working on it.

**Comment by hot22shot** [comment]
Hi,

I also have the same issue, my server is a Synology NAS with DSM 6.2.3-25462, if you need additional logs I can provide them.

**Comment by sam5558** [comment]
Hello,
Same issue on DSM 6.2.3-25426.
~~* When i skip GUAC_USER &  GUAC_PASS i'm getting a blank white page.~~
~~* When i enable authentication i'm getting a "Identifiant Incorrect" error (well may be another issue but still).
Thank you for your hard word~~ (Nevermind)

**Comment by exedox** [comment]
I'm also having the same issue as above. was this ever resolved? is there a working docker?

**Comment by akhan23wgu** [comment]
I submitted a PR that fixes this. #3

**Comment by shlagevuk** [comment]
Hi! 
Thanks a lot @akhan23wgu ! 

I'm reviewing the PR right now before merging

**Comment by shlagevuk** [comment]
Hi!
With the fix pushed by akhan23wgu and a minor change to the docker create command, this issue is solved!
